// =========== GADGET DEFINITIONS ===========
const GADGETS = {
  shelly:  { id:'shelly_g',  name:'バンドエイド',   icon:'🩹', desc:'即座にHP1500回復',        price:800,
             use(p){ p.hp=Math.min(p.maxHp, p.hp+1500); spawnParticles(p.x,p.y,'#4deb4d',12); } },
  colt:    { id:'colt_g',    name:'スピードローダー',icon:'🔄', desc:'弾を即座に全回復',        price:800,
             use(p){ p.ammo=p.maxAmmo; spawnParticles(p.x,p.y,'#4fc3f7',10); } },
  bull:    { id:'bull_g',    name:'バーサーカー',    icon:'💢', desc:'3秒間ダメージ+50%',       price:800,
             use(p){ p._buffDmg=1.5; p._buffTimer=3.0; spawnParticles(p.x,p.y,'#66bb6a',14); } },
  brock:   { id:'brock_g',   name:'ロケットサポート',icon:'🚀', desc:'前方に大爆発ロケット',    price:800,
             use(p){ for(let i=-1;i<=1;i++) state.bullets.push({x:p.x,y:p.y,vx:Math.cos(p.facing+i*0.15)*420,vy:Math.sin(p.facing+i*0.15)*420,r:9,dmg:2500,owner:p,life:1.0,isRocket:true,col:p.col}); } },
  spike:   { id:'spike_g',   name:'スパイクボム',    icon:'💣', desc:'周囲360°にスパイク',      price:800,
             use(p){ for(let i=0;i<12;i++){const a=i/12*Math.PI*2; state.bullets.push({x:p.x,y:p.y,vx:Math.cos(a)*260,vy:Math.sin(a)*260,r:5,dmg:600,owner:p,life:0.9,isRocket:false,col:'#ab47bc'});} } },
  leon:    { id:'leon_g',    name:'スモークスクリーン',icon:'💨',desc:'2秒間無敵（被弾無効）',  price:800,
             use(p){ p.invTimer=2.0; spawnParticles(p.x,p.y,'#26c6da',16); } },
  nita:    { id:'nita_g',    name:'パワーブースト',  icon:'⚡', desc:'スーパーを即座に発動',    price:800,
             use(p){ p.superCharge=p.maxSuper; spawnParticles(p.x,p.y,'#8d6e63',10); } },
  jessie:  { id:'jessie_g',  name:'コイルリリース',  icon:'🌀', desc:'前方に電撃ビーム',        price:800,
             use(p){ for(let i=0;i<3;i++) state.bullets.push({x:p.x,y:p.y,vx:Math.cos(p.facing+i*0.08)*500,vy:Math.sin(p.facing+i*0.08)*500,r:6,dmg:1200,owner:p,life:0.7,isRocket:false,col:'#ffeb3b'});} },
  piper:   { id:'piper_g',   name:'パラシュート',    icon:'🪂', desc:'一瞬テレポート（前方150px）',price:800,
             use(p){ const nx=p.x+Math.cos(p.facing)*150; const ny=p.y+Math.sin(p.facing)*150; if(nx>p.r&&nx<MPX-p.r&&ny>p.r&&ny<MPY-p.r){p.x=nx;p.y=ny;} spawnParticles(p.x,p.y,'#f48fb1',12); } },
  penny:   { id:'penny_g',   name:'コインボム',      icon:'🪙', desc:'広範囲に爆発弾3発',       price:800,
             use(p){ for(let i=0;i<3;i++){const a=p.facing+(i-1)*0.25; state.bullets.push({x:p.x,y:p.y,vx:Math.cos(a)*320,vy:Math.sin(a)*320,r:8,dmg:1800,owner:p,life:1.1,isRocket:true,col:'#ffca28'});} } },
  rico:    { id:'rico_g',    name:'リコシェブースト', icon:'🔀', desc:'全方向8発バウンス弾',     price:800,
             use(p){ for(let i=0;i<8;i++){const a=i/8*Math.PI*2; state.bullets.push({x:p.x,y:p.y,vx:Math.cos(a)*380,vy:Math.sin(a)*380,r:5,dmg:700,owner:p,life:1.0,isRocket:false,col:'#4db6ac'});} } },
  rosa:    { id:'rosa_g',    name:'ソーンアーマー',   icon:'🛡️', desc:'3秒間ダメージ75%カット', price:800,
             use(p){ p._armor=0.25; p._armorTimer=3.0; spawnParticles(p.x,p.y,'#81c784',14); } },
  darryl:  { id:'darryl_g',  name:'ローリングリロード',icon:'🔃',desc:'弾を全回復+移動速度2倍(2秒)',price:800,
             use(p){ p.ammo=p.maxAmmo; p._speedBuff=2.0; p._speedTimer=2.0; spawnParticles(p.x,p.y,'#90a4ae',10); } },
  crow:    { id:'crow_g',    name:'ポイズンスピード',  icon:'☠️', desc:'移動速度+50%(3秒)+毒弾', price:800,
             use(p){ p._speedBuff=1.5; p._speedTimer=3.0; spawnParticles(p.x,p.y,'#78909c',12); } },
  mortis:  { id:'mortis_g',  name:'バットガジェット',  icon:'🦇', desc:'HP2000回復+周囲ダメージ', price:800,
             use(p){ p.hp=Math.min(p.maxHp,p.hp+2000); for(const e of state.enemies){if(e.alive&&dist(p,e)<120){e.hp-=800;if(e.hp<=0)killEnemy(e,'player');}} spawnParticles(p.x,p.y,'#7e57c2',16); } },
  zara:    { id:'zara_g',    name:'フレイムバースト', icon:'🔥', desc:'前方に炎の波3発',         price:800,
             use(p){ for(let i=-1;i<=1;i++) state.bullets.push({x:p.x,y:p.y,vx:Math.cos(p.facing+i*0.2)*400,vy:Math.sin(p.facing+i*0.2)*400,r:8,dmg:1400,owner:p,life:0.8,isRocket:false,col:'#ff5722'}); } },
  kuro:    { id:'kuro_g',    name:'シャドウステップ', icon:'🌑', desc:'2秒無敵+瞬間移動',        price:800,
             use(p){ p.invTimer=2.0; const nx=p.x+Math.cos(p.facing)*180,ny=p.y+Math.sin(p.facing)*180; if(nx>p.r&&nx<MPX-p.r&&ny>p.r&&ny<MPY-p.r){p.x=nx;p.y=ny;} spawnParticles(p.x,p.y,'#424242',14); } },
  volta:   { id:'volta_g',   name:'サンダーチャージ', icon:'⚡', desc:'周囲4方向に稲妻弾',       price:800,
             use(p){ for(let i=0;i<4;i++){const a=p.facing+i*Math.PI/2; state.bullets.push({x:p.x,y:p.y,vx:Math.cos(a)*450,vy:Math.sin(a)*450,r:5,dmg:1000,owner:p,life:0.8,isRocket:false,col:'#ffeb3b'});} } },
  mira:    { id:'mira_g',    name:'アイスシールド',   icon:'🧊', desc:'3秒ダメージ60%カット',    price:800,
             use(p){ p._armor=0.4; p._armorTimer=3.0; spawnParticles(p.x,p.y,'#00bcd4',12); } },
  goro:    { id:'goro_g',    name:'グラウンドスマッシュ',icon:'👊',desc:'近距離全方向超ダメージ', price:800,
             use(p){ for(const e of state.enemies){if(e.alive&&dist(p,e)<160){e.hp-=2500;if(e.hp<=0)killEnemy(e,'player');}} spawnParticles(p.x,p.y,'#795548',18); } },
  nyx:     { id:'nyx_g',     name:'スターゲート',     icon:'🌟', desc:'最寄り敵の後ろにテレポート',price:800,
             use(p){ let nearest=null,nd=Infinity; state.enemies.forEach(e=>{if(e.alive){const d=dist(p,e);if(d<nd){nd=d;nearest=e;}}}); if(nearest&&nd<400){p.x=nearest.x-Math.cos(nearest.facing)*60;p.y=nearest.y-Math.sin(nearest.facing)*60;} spawnParticles(p.x,p.y,'#3f51b5',12); } },
  blast:   { id:'blast_g',   name:'メガボム',         icon:'💥', desc:'超大爆発ロケット1発',     price:800,
             use(p){ state.bullets.push({x:p.x,y:p.y,vx:Math.cos(p.facing)*380,vy:Math.sin(p.facing)*380,r:14,dmg:3500,owner:p,life:1.0,isRocket:true,col:'#ff5722'}); } },
  ivy:     { id:'ivy_g',     name:'バインドルーツ',   icon:'🌿', desc:'移動速度+40%(3秒)',        price:800,
             use(p){ p._speedBuff=1.4; p._speedTimer=3.0; spawnParticles(p.x,p.y,'#4caf50',10); } },
  rex:     { id:'rex_g',     name:'レックスロア',     icon:'🦖', desc:'HP3000回復',              price:800,
             use(p){ p.hp=Math.min(p.maxHp,p.hp+3000); spawnParticles(p.x,p.y,'#ff6d00',16); } },
  wave:    { id:'wave_g',    name:'ウォータージェット',icon:'💧', desc:'前方に高速水弾6連',       price:800,
             use(p){ for(let i=0;i<6;i++) setTimeout(()=>{ if(state.running) state.bullets.push({x:p.x,y:p.y,vx:Math.cos(p.facing)*480,vy:Math.sin(p.facing)*480,r:5,dmg:700,owner:p,life:0.7,isRocket:false,col:'#03a9f4'}); },i*80); } },
  zorn:    { id:'zorn_g',    name:'デモンオーラ',     icon:'😈', desc:'5秒間ダメージ+70%',       price:800,
             use(p){ p._buffDmg=1.7; p._buffTimer=5.0; spawnParticles(p.x,p.y,'#b71c1c',16); } },
  kira:    { id:'kira_g',    name:'スターシャワー',   icon:'🌠', desc:'上空から星弾5発降下',     price:800,
             use(p){ for(let i=0;i<5;i++){const ax=p.x+rand(-100,100),ay=p.y+rand(-100,100); setTimeout(()=>spawnParticles(ax,ay,'#f9a825',10),i*150); setTimeout(()=>{ state.enemies.forEach(e=>{if(e.alive&&dist({x:ax,y:ay},e)<60){e.hp-=900;if(e.hp<=0)killEnemy(e,'player');}}); },i*150+50); } } },
  punk:    { id:'punk_g',    name:'デスメタルソロ',   icon:'🎸', desc:'周囲360°音波12発',        price:800,
             use(p){ for(let i=0;i<12;i++){const a=i/12*Math.PI*2; state.bullets.push({x:p.x,y:p.y,vx:Math.cos(a)*300,vy:Math.sin(a)*300,r:5,dmg:550,owner:p,life:0.9,isRocket:false,col:'#e91e63'});} } },
  titan:   { id:'titan_g',   name:'シールドモード',   icon:'🛡️', desc:'5秒間ダメージ80%カット',   price:800,
             use(p){ p._armor=0.2; p._armorTimer=5.0; spawnParticles(p.x,p.y,'#607d8b',14); } },
  swift:   { id:'swift_g',   name:'ソニックブレード', icon:'💨', desc:'超高速で前方に突進しながら弾',price:800,
             use(p){ const nx=p.x+Math.cos(p.facing)*200,ny=p.y+Math.sin(p.facing)*200; if(nx>p.r&&nx<MPX-p.r){p.x=nx;} if(ny>p.r&&ny<MPY-p.r){p.y=ny;} for(let i=0;i<3;i++) state.bullets.push({x:p.x,y:p.y,vx:Math.cos(p.facing+rand(-0.2,0.2))*420,vy:Math.sin(p.facing+rand(-0.2,0.2))*420,r:5,dmg:700,owner:p,life:0.5,isRocket:false,col:'#00e676'}); spawnParticles(p.x,p.y,'#00e676',12); } },
  flint:   { id:'flint_g',   name:'スモークボム',     icon:'💨', desc:'2秒間煙幕(invTimer)',       price:800,
             use(p){ p.invTimer=2.0; spawnParticles(p.x,p.y,'#8d6e63',10); } },
  aurora:  { id:'aurora_g',  name:'オーロラシールド', icon:'🌌', desc:'3秒ダメージ70%カット',      price:800,
             use(p){ p._armor=0.3; p._armorTimer=3.0; spawnParticles(p.x,p.y,'#80cbc4',12); } },
  drago:   { id:'drago_g',   name:'ドラゴンクロー',   icon:'🐉', desc:'近距離全方向超火力',        price:800,
             use(p){ for(let i=0;i<8;i++){const a=i/8*Math.PI*2; state.bullets.push({x:p.x,y:p.y,vx:Math.cos(a)*280,vy:Math.sin(a)*280,r:7,dmg:1600,owner:p,life:0.6,isRocket:false,col:'#ef5350'});} spawnParticles(p.x,p.y,'#ff5722',14); } },
  echo:    { id:'echo_g',    name:'ソナーパルス',     icon:'🔊', desc:'全方向音波弾10発',          price:800,
             use(p){ for(let i=0;i<10;i++){const a=i/10*Math.PI*2; state.bullets.push({x:p.x,y:p.y,vx:Math.cos(a)*340,vy:Math.sin(a)*340,r:4,dmg:600,owner:p,life:0.9,isRocket:false,col:'#7c4dff'});} } },
  terra:   { id:'terra_g',   name:'グラウンドスピア',  icon:'🪨', desc:'地面から岩石3発生成',      price:800,
             use(p){ for(let i=-1;i<=1;i++){const a=p.facing+i*0.18; state.bullets.push({x:p.x,y:p.y,vx:Math.cos(a)*360,vy:Math.sin(a)*360,r:10,dmg:2200,owner:p,life:0.5,isRocket:true,col:'#8d6e63'});} } },
  prism:   { id:'prism_g',   name:'プリズムミラー',   icon:'💎', desc:'3方向に虹色弾',             price:800,
             use(p){ for(let i=0;i<3;i++){const a=p.facing+(i-1)*0.4; state.bullets.push({x:p.x,y:p.y,vx:Math.cos(a)*460,vy:Math.sin(a)*460,r:5,dmg:1000,owner:p,life:0.75,isRocket:false,col:'#e040fb'});} } },
  forge:   { id:'forge_g',   name:'メルトダウン',     icon:'🌋', desc:'超大型溶岩弾1発',           price:800,
             use(p){ state.bullets.push({x:p.x,y:p.y,vx:Math.cos(p.facing)*350,vy:Math.sin(p.facing)*350,r:16,dmg:4000,owner:p,life:0.9,isRocket:true,col:'#ff8f00'}); } },
  aether:  { id:'aether_g',  name:'エーテルヒール',   icon:'✨', desc:'HP全回復+3秒無敵',          price:800,
             use(p){ p.hp=p.maxHp; p.invTimer=3.0; spawnParticles(p.x,p.y,'#e8eaf6',18); } },
  vex:     { id:'vex_g',     name:'ヴェノムクラウド',  icon:'☠️', desc:'毒弾5発前方扇形',          price:800,
             use(p){ for(let i=-2;i<=2;i++){const a=p.facing+i*0.18; state.bullets.push({x:p.x,y:p.y,vx:Math.cos(a)*400,vy:Math.sin(a)*400,r:6,dmg:900,owner:p,life:0.85,isRocket:false,col:'#263238'});} } },
  lumi:    { id:'lumi_g',    name:'ライトフラッシュ',  icon:'💡', desc:'前方に光弾10連射',          price:800,
             use(p){ for(let i=0;i<10;i++) setTimeout(()=>{ if(state.running) state.bullets.push({x:p.x,y:p.y,vx:Math.cos(p.facing)*500,vy:Math.sin(p.facing)*500,r:4,dmg:500,owner:p,life:0.65,isRocket:false,col:'#fff176'}); },i*60); } },
  shampa:  { id:'shampa_g', name:'メガシャワー',      icon:'🚿', desc:'16連続シャンプー弾！',        price:800,
             use(p){ for(let i=0;i<16;i++) setTimeout(()=>{ if(state.running){ const a=p.facing+rand(-0.1,0.1); state.bullets.push({x:p.x,y:p.y,vx:Math.cos(a)*320,vy:Math.sin(a)*320,r:4,dmg:200,owner:p,life:0.85,isRocket:false,col:'#e91e8c'}); }},i*50); } },
  babi:    { id:'babi_g',   name:'ダブルアップ',      icon:'🎰', desc:'3秒間攻撃力確定3倍',         price:800,
             use(p){ p._buffDmg=3.0; p._buffTimer=3.0; spawnParticles(p.x,p.y,'#ff6f00',16); showToast('🎰 ダブルアップ！ダメージ3倍！'); } },
  toss:    { id:'toss_g',   name:'スーパーダッシュ',  icon:'💨', desc:'前方に高速突進ダメージ',     price:800,
             use(p){ p._dashing=true; p._dashDir=p.facing; p._dashSpeed=900; p._dashTimer=0.35; spawnParticles(p.x,p.y,'#5c6bc0',14); } },
  flamma:  { id:'flamma_g', name:'メガバーン',        icon:'🔥', desc:'周囲を炎で包む（3秒DoT）',   price:800,
             use(p){ p._burning=true; p._burnTimer=3.0; spawnParticles(p.x,p.y,'#ff3d00',18); showToast('🔥 メガバーン！周囲に炎ダメージ！'); } },
  mirror:  { id:'mirror_g', name:'ミラーコピー',      icon:'🪞', desc:'弾を3方向に分裂反射',        price:800,
             use(p){ for(let i=-1;i<=1;i++){const a=p.facing+i*0.35; state.bullets.push({x:p.x,y:p.y,vx:Math.cos(a)*400,vy:Math.sin(a)*400,r:5,dmg:p.dmg*1.2,owner:p,life:p.range/400,isRocket:false,col:'#eceff1'});} spawnParticles(p.x,p.y,'#b0bec5',10); } },
  shield:  { id:'shield_g', name:'フォートレス',      icon:'🏰', desc:'5秒間ダメージ90%カット',     price:800,
             use(p){ p._armor=0.1; p._armorTimer=5.0; spawnParticles(p.x,p.y,'#607d8b',16); showToast('🏰 フォートレス！ほぼ無敵！'); } },
  ghost:   { id:'ghost_g',  name:'ファントムヴェール', icon:'👻', desc:'3秒完全透明（被弾無効）',    price:800,
             use(p){ p.invTimer=3.0; p._ghosting=true; setTimeout(()=>{ if(state.player) state.player._ghosting=false; },3000); spawnParticles(p.x,p.y,'#e0e0e0',14); showToast('👻 消えた！3秒間無敵！'); } },
  dyna:    { id:'dyna_g',   name:'ボムレイン',        icon:'💣', desc:'上空から爆弾5発降下',        price:800,
             use(p){ for(let i=0;i<5;i++){ const tx=p.x+rand(-180,180), ty=p.y+rand(-180,180); setTimeout(()=>{ spawnExplosion(tx,ty); state.enemies.forEach(e=>{if(e.alive&&dist({x:tx,y:ty},e)<80){e.hp-=1200;if(e.hp<=0)killEnemy(e,'player');}}); spawnParticles(tx,ty,'#ffd600',12); },300+i*200); } } },
  quake:   { id:'quake_g',  name:'メガクエイク',     icon:'🌋', desc:'周囲全体に地震波ダメージ',    price:800,
             use(p){ for(const e of state.enemies){if(e.alive&&dist(p,e)<200){e.hp-=1800;e.invTimer=0.5;if(e.hp<=0)killEnemy(e,'player');}} spawnParticles(p.x,p.y,'#8d6e63',20); showToast('🌋 メガクエイク！'); } },
  neon:    { id:'neon_g',   name:'ネオンバースト',   icon:'⚡', desc:'20連続ネオン弾一気発射',     price:800,
             use(p){ for(let i=0;i<20;i++) setTimeout(()=>{ if(!state.running) return; const a=p.facing+rand(-0.08,0.08); state.bullets.push({x:p.x,y:p.y,vx:Math.cos(a)*520,vy:Math.sin(a)*520,r:3,dmg:180,owner:p,life:0.65,isRocket:false,col:'#84ffff'}); },i*40); } },
  comet:   { id:'comet_g',  name:'ブラックホール',  icon:'🌌', desc:'前方に強力な引力を発生',     price:800,
             use(p){ const bx=p.x+Math.cos(p.facing)*200, by=p.y+Math.sin(p.facing)*200; for(const e of state.enemies){if(e.alive){const ang=Math.atan2(by-e.y,bx-e.x); e.x+=Math.cos(ang)*80; e.y+=Math.sin(ang)*80; if(dist({x:bx,y:by},e)<50){e.hp-=1500;if(e.hp<=0)killEnemy(e,'player');}}} spawnParticles(bx,by,'#e040fb',20); } },
  viper:   { id:'viper_g',  name:'ポイズンクラウド', icon:'☠️', desc:'毒の雲を設置（3秒間持続）',  price:800,
             use(p){ p._poisonCloud={x:p.x,y:p.y,timer:3.0}; spawnParticles(p.x,p.y,'#558b2f',16); showToast('☠️ ポイズンクラウド設置！'); } },
  gatling: { id:'gatling_g',name:'ミニガン',         icon:'🔫', desc:'5秒間攻撃力+60%・速度-20%', price:800,
             use(p){ p._buffDmg=1.6; p._buffTimer=5.0; p._speedBuff=0.8; p._speedTimer=5.0; spawnParticles(p.x,p.y,'#546e7a',14); } },
  witch:   { id:'witch_g',  name:'カース',           icon:'🧿', desc:'最近3体の敵を3秒スロー',    price:800,
             use(p){ let cnt=0; const sorted=[...state.enemies].filter(e=>e.alive).sort((a,b)=>dist(p,a)-dist(p,b)); sorted.slice(0,3).forEach(e=>{e._slowed=true; e._slowTimer=3.0; spawnParticles(e.x,e.y,'#6a1b9a',8);}); showToast('🧿 カース！敵3体スロー！'); } },
  boulder: { id:'boulder_g',name:'ランブル',         icon:'🪨', desc:'巨大岩を転がして貫通攻撃',   price:800,
             use(p){ state.bullets.push({x:p.x,y:p.y,vx:Math.cos(p.facing)*300,vy:Math.sin(p.facing)*300,r:18,dmg:2200,owner:p,life:1.2,isRocket:false,col:'#795548',_pierce:true}); spawnParticles(p.x,p.y,'#8d6e63',10); } },
  spark:   { id:'spark_g',  name:'サンダーストーム', icon:'🌩️', desc:'全敵にランダム雷落とす',     price:800,
             use(p){ state.enemies.forEach(e=>{if(!e.alive) return; setTimeout(()=>{ spawnParticles(e.x,e.y,'#fff176',10); e.hp-=700+rand(0,500); if(e.hp<=0) killEnemy(e,'player'); }, rand(0,800)); }); showToast('🌩️ サンダーストーム！'); } },
  freeze:  { id:'freeze_g', name:'アイスエイジ',     icon:'🧊', desc:'全敵を2秒間完全停止',       price:800,
             use(p){ state.enemies.forEach(e=>{if(e.alive){e._frozen=true; e._frozenTimer=2.0; spawnParticles(e.x,e.y,'#b3e5fc',8);}}); showToast('🧊 アイスエイジ！全敵凍結！'); } },
  phantom: { id:'phantom_g',name:'ブリンクストライク',icon:'👾', desc:'3回連続テレポート攻撃',     price:800,
             use(p){ for(let i=0;i<3;i++) setTimeout(()=>{ if(!state.running||!p.alive) return; let nearest=null,nd=Infinity; state.enemies.forEach(e=>{if(e.alive){const d=dist(p,e);if(d<nd){nd=d;nearest=e;}}}); if(nearest&&nd<350){p.x=nearest.x+Math.cos(p.facing+Math.PI)*50; p.y=nearest.y+Math.sin(p.facing+Math.PI)*50; nearest.hp-=900; if(nearest.hp<=0) killEnemy(nearest,'player'); spawnParticles(p.x,p.y,'#f06292',8);} },i*300); } },
  // レア
  blaze:   { id:'blaze_g',  name:'フレアボム',        icon:'🔥', desc:'前方に炎の球3発投下',        price:800,
             use(p){ for(let i=-1;i<=1;i++){const a=p.facing+i*0.25; state.bullets.push({x:p.x,y:p.y,vx:Math.cos(a)*330,vy:Math.sin(a)*330,r:8,dmg:1400,owner:p,life:0.9,isRocket:true,col:'#ff6f00'});} spawnParticles(p.x,p.y,'#ff6f00',12); } },
  zapp:    { id:'zapp_g',   name:'オーバーチャージ',  icon:'⚡', desc:'5秒間弾速+50%・連射2倍',    price:800,
             use(p){ p._buffDmg=1.4; p._buffTimer=5.0; p.reloadTime*=0.5; setTimeout(()=>{if(p) p.reloadTime*=2;},5000); spawnParticles(p.x,p.y,'#ffd600',14); showToast('⚡ オーバーチャージ！'); } },
  coral:   { id:'coral_g',  name:'バブルシールド',    icon:'🫧', desc:'泡で3秒間ダメージ60%カット', price:800,
             use(p){ p._armor=0.4; p._armorTimer=3.0; spawnParticles(p.x,p.y,'#00bcd4',12); } },
  rusty:   { id:'rusty_g',  name:'スクラップアーマー',icon:'🔩', desc:'HP2500回復＋装甲3秒',       price:800,
             use(p){ p.hp=Math.min(p.maxHp,p.hp+2500); p._armor=0.5; p._armorTimer=3.0; spawnParticles(p.x,p.y,'#a1887f',10); } },
  pip:     { id:'pip_g',    name:'ストーンレイン',     icon:'🪨', desc:'上から石が10個降る',        price:800,
             use(p){ for(let i=0;i<10;i++) setTimeout(()=>{ const tx=p.x+rand(-200,200),ty=p.y+rand(-200,200); state.enemies.forEach(e=>{if(e.alive&&dist({x:tx,y:ty},e)<55){e.hp-=600;if(e.hp<=0)killEnemy(e,'player');}}); spawnParticles(tx,ty,'#ce93d8',6); },i*120); } },
  // ウルトラレジェンダリー
  godrix:  { id:'godrix_g', name:'神の裁き',           icon:'⚡', desc:'全敵に即時3000ダメージ',    price:1500,
             use(p){ state.enemies.forEach(e=>{if(e.alive){e.hp-=3000;spawnParticles(e.x,e.y,'#d50000',14);if(e.hp<=0)killEnemy(e,'player');}});showToast('⚡ 神の裁き！全敵に3000ダメージ！'); } },
  seraph:  { id:'seraph_g', name:'聖なる光',           icon:'✨', desc:'HP全回復＋味方全員回復',    price:1500,
             use(p){ p.hp=p.maxHp; state.enemies.filter(e=>e.isFriendBot).forEach(e=>{e.hp=e.maxHp;}); spawnParticles(p.x,p.y,'#ffd740',20); showToast('✨ 聖なる光！HP全回復！'); } },
  void:    { id:'void_g',   name:'虚空の門',           icon:'🌀', desc:'全敵をプレイヤーの元に引き寄せ',price:1500,
             use(p){ state.enemies.forEach(e=>{if(!e.alive) return; const ang=Math.atan2(p.y-e.y,p.x-e.x); e.x+=Math.cos(ang)*180; e.y+=Math.sin(ang)*180; e.hp-=1000; if(e.hp<=0)killEnemy(e,'player');}); spawnParticles(p.x,p.y,'#7c4dff',18); showToast('🌀 虚空の門！全敵を引き寄せ！'); } },
  nova:    { id:'nova_g',   name:'ノヴァ爆発',         icon:'💫', desc:'超広範囲に星の爆発',        price:1500,
             use(p){ for(let i=0;i<24;i++){const a=i/24*Math.PI*2; state.bullets.push({x:p.x,y:p.y,vx:Math.cos(a)*450,vy:Math.sin(a)*450,r:6,dmg:1800,owner:p,life:1.1,isRocket:false,col:'#00e5ff'});} spawnParticles(p.x,p.y,'#ffffff',24); showToast('💫 ノヴァ爆発！'); } },
  kronos:  { id:'kronos_g', name:'時間停止',           icon:'⏱️', desc:'全敵を4秒間完全停止',       price:1500,
             use(p){ state.enemies.forEach(e=>{if(e.alive){e._frozen=true;e._frozenTimer=4.0;spawnParticles(e.x,e.y,'#7c4dff',8);}});showToast('⏱️ 時間停止！全敵4秒間停止！'); } },
  inferna: { id:'inferna_g',name:'メルトダウン',        icon:'🌋', desc:'フィールド全体に炎ダメージ',  price:1500,
             use(p){ state.enemies.forEach(e=>{if(!e.alive) return; e.hp-=2500; e._burnDot=true; e._burnTimer=3.0; if(e.hp<=0)killEnemy(e,'player');}); spawnParticles(p.x,p.y,'#ff3d00',22); showToast('🌋 メルトダウン！フィールド炎上！'); } },
  azura:   { id:'azura_g',  name:'大津波',             icon:'🌊', desc:'全方向に巨大水波',           price:1500,
             use(p){ for(let i=0;i<16;i++){const a=i/16*Math.PI*2; state.bullets.push({x:p.x,y:p.y,vx:Math.cos(a)*380,vy:Math.sin(a)*380,r:12,dmg:2800,owner:p,life:1.3,isRocket:false,col:'#1565c0'});} spawnParticles(p.x,p.y,'#29b6f6',20); } },
  terron:  { id:'terron_g', name:'地殻変動',           icon:'💥', desc:'地割れで全敵を2500ダメージ', price:1500,
             use(p){ state.enemies.forEach(e=>{if(!e.alive) return; e.hp-=2500; if(e.hp<=0)killEnemy(e,'player');}); for(let i=0;i<20;i++) spawnParticles(p.x+rand(-250,250),p.y+rand(-250,250),'#33691e',8); showToast('💥 地殻変動！全敵に2500ダメージ！'); } },
  spectra: { id:'spectra_g',name:'スペクトラムレーザー',icon:'🌈', desc:'虹色レーザーを6方向発射',    price:1500,
             use(p){ const cols=['#ef5350','#ff9800','#ffeb3b','#4caf50','#2196f3','#9c27b0']; for(let i=0;i<6;i++){const a=p.facing+i*Math.PI/3; state.bullets.push({x:p.x,y:p.y,vx:Math.cos(a)*520,vy:Math.sin(a)*520,r:7,dmg:2200,owner:p,life:1.0,isRocket:false,col:cols[i]});} spawnParticles(p.x,p.y,'#f50057',16); } },
  abyssal: { id:'abyssal_g',name:'深淵召喚',           icon:'🌊', desc:'全敵を毒＋スロー＋ダメージ',  price:1500,
             use(p){ state.enemies.forEach(e=>{if(!e.alive) return; e.hp-=1500; e._slowed=true; e._slowTimer=4.0; e._poisonDot=true; e._poisonTimer=4.0; if(e.hp<=0)killEnemy(e,'player');}); spawnParticles(p.x,p.y,'#1de9b6',20); showToast('🌊 深淵召喚！全敵に複合デバフ！'); } },
  // スーパーレア素手系
  knux:    { id:'knux_g',   name:'ラッシュアタック', icon:'👊', desc:'前方に高速4連パンチ',        price:800,
             use(p){ for(let i=0;i<4;i++) setTimeout(()=>{ const nx=p.x+Math.cos(p.facing)*(60+i*45),ny=p.y+Math.sin(p.facing)*(60+i*45); state.enemies.forEach(e=>{if(e.alive&&dist({x:nx,y:ny},e)<55){e.hp-=1200;if(e.hp<=0)killEnemy(e,'player');}}); spawnParticles(nx,ny,'#e53935',6); },i*100); } },
  brawny:  { id:'brawny_g', name:'スーパーアッパー', icon:'🥊', desc:'正面を吹き飛ばす超パンチ',    price:800,
             use(p){ const nx=p.x+Math.cos(p.facing)*140,ny=p.y+Math.sin(p.facing)*140; state.enemies.forEach(e=>{if(e.alive&&dist({x:nx,y:ny},e)<90){e.hp-=3500;e.vx=Math.cos(p.facing)*400;e.vy=Math.sin(p.facing)*400;if(e.hp<=0)killEnemy(e,'player');}}); spawnParticles(nx,ny,'#f57c00',16); } },
  striker: { id:'striker_g',name:'ジャンプキック',   icon:'🦵', desc:'テレポート＋キック攻撃',      price:800,
             use(p){ const nx=p.x+Math.cos(p.facing)*160,ny=p.y+Math.sin(p.facing)*160; if(nx>p.r&&nx<MPX-p.r&&ny>p.r&&ny<MPY-p.r){p.x=nx;p.y=ny;} state.enemies.forEach(e=>{if(e.alive&&dist(p,e)<80){e.hp-=2000;if(e.hp<=0)killEnemy(e,'player');}}); spawnParticles(p.x,p.y,'#1e88e5',12); } },
  crusher: { id:'crusher_g',name:'クラッシャーボム', icon:'💪', desc:'周囲全体に地震ダメージ',      price:800,
             use(p){ state.enemies.forEach(e=>{if(e.alive&&dist(p,e)<200){e.hp-=2500;if(e.hp<=0)killEnemy(e,'player');}}); spawnParticles(p.x,p.y,'#6d4c41',20); showToast('💪 クラッシャー！全体ダメ！'); } },
  whirl:   { id:'whirl_g',  name:'スピンモード',     icon:'🌀', desc:'3秒間回転攻撃が自動発動',    price:800,
             use(p){ p._spinning=true; p._spinTimer=3.0; spawnParticles(p.x,p.y,'#00897b',14); showToast('🌀 スピンモード！'); } },
  // レア素手系
  jab:     { id:'jab_g',    name:'ジャブ乱れ打ち',  icon:'👊', desc:'6連続ジャブ前方',           price:800,
             use(p){ for(let i=0;i<6;i++) setTimeout(()=>{ if(!state.running) return; const a=p.facing+rand(-0.15,0.15); state.bullets.push({x:p.x,y:p.y,vx:Math.cos(a)*420,vy:Math.sin(a)*420,r:5,dmg:400,owner:p,life:0.38,isRocket:false,col:'#f06292'}); },i*60); } },
  pummel:  { id:'pummel_g', name:'パンメル',         icon:'🥊', desc:'前方に連打（5発）',          price:800,
             use(p){ for(let i=0;i<5;i++) setTimeout(()=>{ if(!state.running) return; state.bullets.push({x:p.x+Math.cos(p.facing)*50,y:p.y+Math.sin(p.facing)*50,vx:Math.cos(p.facing)*380,vy:Math.sin(p.facing)*380,r:6,dmg:480,owner:p,life:0.4,isRocket:false,col:'#7986cb'}); },i*80); } },
  slap:    { id:'slap_g',   name:'ビンタ嵐',         icon:'🖐️', desc:'左右に広範囲スラップ',      price:800,
             use(p){ for(let i=-2;i<=2;i++){const a=p.facing+i*0.3; state.bullets.push({x:p.x,y:p.y,vx:Math.cos(a)*360,vy:Math.sin(a)*360,r:5,dmg:420,owner:p,life:0.42,isRocket:false,col:'#aed581'});} } },
  bonk:    { id:'bonk_g',   name:'メガボンク',        icon:'🔔', desc:'超威力ボンク1発',           price:800,
             use(p){ state.bullets.push({x:p.x+Math.cos(p.facing)*40,y:p.y+Math.sin(p.facing)*40,vx:Math.cos(p.facing)*280,vy:Math.sin(p.facing)*280,r:18,dmg:2500,owner:p,life:0.6,isRocket:false,col:'#ffb300'}); spawnParticles(p.x,p.y,'#ffb300',12); } },
  smack:   { id:'smack_g',  name:'クイックスマック', icon:'✊', desc:'超高速10連スマック',          price:800,
             use(p){ for(let i=0;i<10;i++) setTimeout(()=>{ if(!state.running) return; const a=p.facing+rand(-0.1,0.1); state.bullets.push({x:p.x,y:p.y,vx:Math.cos(a)*480,vy:Math.sin(a)*480,r:3,dmg:380,owner:p,life:0.32,isRocket:false,col:'#26c6da'}); },i*45); } },
  // エピック爆弾系
  grenader:{ id:'grenader_g',name:'グレネードラッシュ',icon:'💣', desc:'5連グレネード投下',         price:800,
             use(p){ for(let i=0;i<5;i++){const a=p.facing+rand(-0.3,0.3); state.bullets.push({x:p.x,y:p.y,vx:Math.cos(a)*300,vy:Math.sin(a)*300,r:9,dmg:1600,owner:p,life:1.0,isRocket:true,col:'#558b2f'});} } },
  boomer:  { id:'boomer_g', name:'クラスター',        icon:'💥', desc:'爆弾3発同時投下',            price:800,
             use(p){ for(let i=-1;i<=1;i++){const a=p.facing+i*0.22; state.bullets.push({x:p.x,y:p.y,vx:Math.cos(a)*280,vy:Math.sin(a)*280,r:12,dmg:2200,owner:p,life:1.1,isRocket:true,col:'#e64a19'});} } },
  kaboom:  { id:'kaboom_g', name:'ビッグカブーム',    icon:'🌋', desc:'超巨大爆弾1発',              price:800,
             use(p){ state.bullets.push({x:p.x,y:p.y,vx:Math.cos(p.facing)*240,vy:Math.sin(p.facing)*240,r:20,dmg:3800,owner:p,life:1.3,isRocket:true,col:'#fdd835'}); spawnParticles(p.x,p.y,'#fdd835',14); } },
  // ミシック素手系
  titan3:  { id:'titan3_g', name:'神殴り',            icon:'⚡', desc:'全敵に2800ダメージ',         price:800,
             use(p){ state.enemies.forEach(e=>{if(e.alive){e.hp-=2800;if(e.hp<=0)killEnemy(e,'player');}}); spawnParticles(p.x,p.y,'#4a148c',20); showToast('⚡ 神殴り！全敵2800！'); } },
  wrath:   { id:'wrath_g',  name:'バーサーク',        icon:'😤', desc:'3秒ダメ3倍＋速度2倍',       price:800,
             use(p){ p._buffDmg=3.0; p._buffTimer=3.0; p._speedBuff=2.0; p._speedTimer=3.0; spawnParticles(p.x,p.y,'#b71c1c',18); showToast('😤 バーサーク！ダメ3倍・速2倍！'); } },
  golem:   { id:'golem_g',  name:'ゴーレムクラッシュ',icon:'🪨', desc:'周囲300px全敵に巨大ダメ',   price:800,
             use(p){ state.enemies.forEach(e=>{if(e.alive&&dist(p,e)<300){e.hp-=3500;if(e.hp<=0)killEnemy(e,'player');}});for(let i=0;i<20;i++)spawnParticles(p.x+rand(-150,150),p.y+rand(-150,150),'#37474f',8);showToast('🪨 ゴーレムクラッシュ！'); } },
  // レジェンダリー弓系
  archer:  { id:'archer_g', name:'矢の雨',            icon:'🏹', desc:'前方扇形に矢15本',           price:800,
             use(p){ for(let i=0;i<15;i++){const a=p.facing+(i-7)*0.08; state.bullets.push({x:p.x,y:p.y,vx:Math.cos(a)*520,vy:Math.sin(a)*520,r:4,dmg:1100,owner:p,life:0.95,isRocket:false,col:'#4caf50'});} } },
  elven:   { id:'elven_g',  name:'エルフの嵐',        icon:'🌿', desc:'全方向20本の矢',             price:800,
             use(p){ for(let i=0;i<20;i++){const a=i/20*Math.PI*2; state.bullets.push({x:p.x,y:p.y,vx:Math.cos(a)*500,vy:Math.sin(a)*500,r:3,dmg:900,owner:p,life:1.1,isRocket:false,col:'#80cbc4'});} } },
  // ウルトラレジェンダリー HEXARM
  hexarm:  { id:'hexarm_g', name:'ヘキサバースト',    icon:'✨', desc:'6方向×3=18発の爆裂弾',       price:1500,
             use(p){ for(let i=0;i<18;i++){const a=i/18*Math.PI*2; state.bullets.push({x:p.x,y:p.y,vx:Math.cos(a)*420,vy:Math.sin(a)*420,r:7,dmg:2000,owner:p,life:1.1,isRocket:false,col:'#b388ff'});} spawnParticles(p.x,p.y,'#7c4dff',24); showToast('✨ ヘキサバースト！18発爆裂！'); } },
};

